const IMAGES = {
    LOAD: 'LOAD_IMAGES',
    LOAD_SUCCESS: 'LOAD_SUCCESS',
    LOAD_FAILURE: 'LOAD_FAILURE '
}

const STATS = {
    LOAD: 'LOAD_STATS',
    LOAD_SUCCESS: 'STATS_SUCCESS',
    LOAD_FAILURE: 'STATS_FAILURE '
}

export { IMAGES, STATS }